### ISSUE TITLE
URL in the email points to a random url

### ISSUE THREAD

**Issue by yamila-moreno** [dont-worry-be-happy/dwbh-front#24]
it points to `mydomain.com` (it's not in the code, nor in the configuration compose); if I change the domain with the good one, the parameters seem to be ok.

**Comment by bameda** [comment]
Emails are sent by the backend, @mariogarcia ???

**Comment by mariogarcia** [comment]
Already solved. It needs to be specified in backend `application.yml`

```yaml
# to resolve application links (e.g. mails)
urlresolver:
  host: http://localhost:9000
```

Closing this
